.github/workflows/main.yaml, Makefile, cookiecutter.json, hooks/post_gen_project.py, {{cookiecutter.project_slug}}/CONTRIBUTING.md, {{cookiecutter.project_slug}}/INSTALLATION.md, {{cookiecutter.project_slug}}/Makefile, {{cookiecutter.project_slug}}/docs/conf.py, {{cookiecutter.project_slug}}/mkdocs.yaml
=> feat: Add initial version for OSL

.github/PULL_REQUEST_TEMPLATE.md, {{cookiecutter.project_slug}}/.github/PULL_REQUEST_TEMPLATE.md
Creating an PR Template to the project and also to the cookiecutter of the project.
Solving Issue #7 
* Commit your changes and create a Pull Request to see the template working.
This PR is a:
About this PR:
```
```
=> Adding PR template

.github/workflows/main.yaml, .pre-commit-config.yaml, README.md, conda/dev.yaml, cookiecutter.json, poetry.lock, tests/smoke/black.sh, tests/smoke/blue.sh, tests/smoke/jupyter-book.sh, tests/smoke/mkdocs.sh, tests/smoke/sphinx.sh, {{cookiecutter.project_slug}}/LICENSE, {{cookiecutter.project_slug}}/Makefile, {{cookiecutter.project_slug}}/conda/dev.yaml, {{cookiecutter.project_slug}}/pyproject.toml
This PR aims to improve the github CI and adds a new auto format tool: blue
* ```...```
This PR is a:
About this PR:
```
```
=> feat: Add new options for auto format code

.github/workflows/main.yaml
* ```...```
This PR is a:
About this PR:
```
```
=> ci: Fix yaml format

.github/workflows/main.yaml, .github/workflows/release.yaml
This pr aims to update github actions checkout to v3
resolves #57
* ```...```
This PR is a:
About this PR:
```
```
=> chore(ci): update to checkout v3

{{cookiecutter.project_slug}}/.github/workflows/main.yaml, {{cookiecutter.project_slug}}/.github/workflows/release.yaml
Fix release workflow
resolve #44
* ```...```
This PR is a:
About this PR:
```
```
=> fix: Fix release workflow

tests/smoke/base.sh, tests/smoke/black.sh, tests/smoke/blue.sh, tests/smoke/jupyter-book.sh, tests/smoke/mkdocs.sh, tests/smoke/sphinx.sh
This PR aims to fix the smoke test base script in order to accept values with empty space.
* ```...```
This PR is a:
About this PR:
```
```
=> tests: Fix the base smoke test script

.github/workflows/release.yaml, {{cookiecutter.project_slug}}/.github/workflows/release.yaml
fixes #41 
Semantic release github actions: Added name to the semantic release step
* ```...```
This PR is a:
About this PR:
```
```
=>  #41 Semantic release github actions: Add name to the semantic release step 

.github/workflows/release.yaml
Fix publish dir for the documentation
* ```...```
This PR is a:
About this PR:
```
```
=> chore(release): Fix publish dir for the documentation

{{cookiecutter.project_slug}}/.github/workflows/main.yaml, {{cookiecutter.project_slug}}/.github/workflows/release.yaml
Fixes #45 
This PR is a:
About this PR:
```
```
=> Add timeout-minutes

README.md
I have noticed that a project description was missing in the readme file. This would enable the project to be more accessible and increase its usability.
improving documentation 
* ```...```
This PR is a:
About this PR:
```
```
=> Added Description about the project 

.github/workflows/main.yaml, cookiecutter.json, hooks/post_gen_project.py, tests/smoke/governance.sh, {{cookiecutter.project_slug}}/governance/numpy_governance.md, {{cookiecutter.project_slug}}/governance/sciml_governance.md
Research Governance standards
Solve #51 
This PR is a:
About this PR:
```
=> feat: Research Governance standards

.github/workflows/main.yaml, cookiecutter.json, hooks/post_gen_project.py, tests/smoke/roadmap.sh, {{cookiecutter.project_slug}}/roadmap/ignite_roadmap.md
Research roadmap standards for include in template
Solving issue #50
This PR is a:
- [x ] new feature
- [x ] maintenance
About this PR:
- [ x] New and old tests passed locally.
- [ x] I confirm that the issues mentioned were fixed/resolved .
```
=> feat: Research standards for roadmap

{{cookiecutter.project_slug}}/.github/workflows/release.yaml, {{cookiecutter.project_slug}}/Makefile
Improve semantic release github action workflow in template.
@xmnlab 
Solving issue #42
This PR is a:
About this PR:
=> fix(release): improve semantic release github action workflow

{{cookiecutter.project_slug}}/.releaserc.json, {{cookiecutter.project_slug}}/{{cookiecutter.package_slug}}/__init__.py
Fix semantic-release replace plugin configuration.
Solving issue #47 
This PR is a:
- [x ] maintenance
About this PR:
- [x ] it includes tests.
- [x ] New and old tests passed locally.
- [x ] I managed to test the new changes locally
- [x ] I confirm that the issues mentioned were fixed/resolved .
```
=> fix:semantic-release replace plugin configuration

{{cookiecutter.project_slug}}/.github/workflows/release.yaml, {{cookiecutter.project_slug}}/.releaserc.json
Solving issue #43 
This PR is a:
About this PR:
```
=> fix(release): publish from semantic release to pypi

{{cookiecutter.project_slug}}/{{cookiecutter.package_slug}}/__main__.py
Adding __main__.py file in the template
Solving issue #27 
This PR is a:
About this PR:
=> fix: Add __main__ file

README.md, cookiecutter.json, {{cookiecutter.project_slug}}/.pre-commit-config.yaml, {{cookiecutter.project_slug}}/README.md, {{cookiecutter.project_slug}}/docs/index.md, {{cookiecutter.project_slug}}/pyproject.toml, {{cookiecutter.project_slug}}/{{cookiecutter.package_slug}}/__main__.py
Adding pydocstyle as an option to the template and setting pre-commit hook
Solving issue #37
This PR is a:
- [x ] new feature
About this PR:
- [x ] pre-commit hooks were executed locally.
- [x ] New and old tests passed locally.
- [x ] I managed to test the new changes locally
- [ x] I confirm that the issues mentioned were fixed/resolved .
```
=> feat(template): Adding pydocstyle to the template

{{cookiecutter.project_slug}}/README.md, {{cookiecutter.project_slug}}/docs/index.md
Add additional changes to the readme for pydocstyle as a template option
Solving issue #37
This PR is a:
- [ x] new feature
About this PR:
- [X ] pre-commit hooks were executed locally.
- [x ] New and old tests passed locally.
- 
- [ x] I managed to test the new changes locally
```
=> feat(template): Add pydocstyle to the template

README.md
Changed cookiecutter to cookieninja and added the current correct commands to locally test changes made by template users.
This PR is a:
About this PR:
```
=> fix: Improve readme

{{cookiecutter.project_slug}}/.github/workflows/release.yaml
* ```...```
This PR is a:
About this PR:
```
```
=> ci: Remove unnecessary release command in release.yaml

{{cookiecutter.project_slug}}/.pre-commit-config.yaml
Eliminate redundancy in pre-commit-config.yaml
This PR is a:
About this PR:
=> Fix(template): Eliminate redundancy in pre-commit-config.yaml

README.md, cookiecutter.json, {{cookiecutter.project_slug}}/.pre-commit-config.yaml, {{cookiecutter.project_slug}}/README.md, {{cookiecutter.project_slug}}/docs/index.md, {{cookiecutter.project_slug}}/pyproject.toml
Adding McCabe to the template.
Solving issue #35 
This PR is a:
About this PR:
=> feat(template): Adding McCabe to the template.

.github/PULL_REQUEST_TEMPLATE.md, {{cookiecutter.project_slug}}/.github/PULL_REQUEST_TEMPLATE.md
Correction of PRs template 
This PR is a:
- [x ] maintenance
About this PR:
```
=> fix: PR template

{{cookiecutter.project_slug}}/.pre-commit-config.yaml, {{cookiecutter.project_slug}}/README.md, {{cookiecutter.project_slug}}/docs/index.md
When the template is generated for values other than the default values, unnecessary spaces are added. This is fixed here.
To render the template in the affected parts, I used [J2Live](https://j2live.ttl255.com/).
https://jinja.palletsprojects.com/en/3.1.x/templates/
This PR is a:
About this PR:
=> fix(template): Remove unnecessary spaces

README.md, cookiecutter.json, hooks/post_gen_project.py, tests/smoke/containers.sh, {{cookiecutter.project_slug}}/README.md, {{cookiecutter.project_slug}}/containers/Dockerfile, {{cookiecutter.project_slug}}/containers/compose.yaml, {{cookiecutter.project_slug}}/docs/index.md, {{cookiecutter.project_slug}}/pyproject.toml
Adding option for podman and docker with initial files.
Solve #24
This PR is a:
About this PR:
=> feat(template): Adding option for podman and docker + initial files

cookiecutter.json, {{cookiecutter.project_slug}}/.pre-commit-config.yaml, {{cookiecutter.project_slug}}/conda/dev.yaml
solved issue #22 
* ```...```
This PR is a:
About this PR:
```
```
=> Feat(pre-commit) : Added shellcheck to pre-commit hook template.

osl_python_template_cli.py, src/osl_python_template/__main__.py, src/osl_python_template/cli.py
The code is a Python CLI tool that loads prompts from a cookiecutter.json file and displays the user's answers.
issued solved #97 
* ```...```
This PR is a:
About this PR:
```
```
=> Feat(CLI) : Added osl_python_template_cli

.github/workflows/release.yaml, src/scicookie/cli.py
Fix ninjacookie call and improve the release workflow.
* ```...```
This PR is a:
About this PR:
```
```
=> fix: Fix the ninjacookie call

.github/workflows/release.yaml
Fix the release workflow. It was missing an environment variable for pypi token.
* ```...```
This PR is a:
About this PR:
```
```
=> chore(release): Fix the release workflow

pyproject.toml
Fix the release step that replace the version in pyproject.toml
* ```...```
This PR is a:
About this PR:
```
```
=> chore(release): Fix the release step that replace the version in pyproject.toml

.releaserc.json
* ```...```
This PR is a:
About this PR:
```
```
=> chore(release): Fix the pypi release step

src/scicookie/{{cookiecutter.project_slug}}/.pre-commit-config.yaml, src/scicookie/{{cookiecutter.project_slug}}/pyproject.toml
Refactor the linter configuration in the pyproject.toml and pre-commit-config.yaml files in the template side.
* ```...```
This PR is a:
About this PR:
```
```
=> refactor(linters): Refactor the linter configurations used by the template

src/scicookie/{{cookiecutter.project_slug}}/.pre-commit-config.yaml
Follow-up change from #125 
thanks @Anavelyz for pointing that issue
* ```...```
This PR is a:
About this PR:
```
```
=> chore(pre-commit): Remove unncessary file types parameters from pre-commit-config

src/scicookie/hooks/post_gen_project.py, src/scicookie/{{cookiecutter.project_slug}}/build-system/base-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/poetry-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/conda/dev.yaml
* ```...```
This PR is a:
About this PR:
```
```
=> refactor: Create a separated structure for build-system

.makim.yaml, README.md, docs/guide.md, src/scicookie/cookiecutter.json, src/scicookie/hooks/post_gen_project.py, src/scicookie/profiles/base.yaml, src/scicookie/profiles/osl.yaml, src/scicookie/{{cookiecutter.project_slug}}/README.md, src/scicookie/{{cookiecutter.project_slug}}/build-system/flit-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/conda/dev.yaml, src/scicookie/{{cookiecutter.project_slug}}/docs/contributing.md, tests/smoke/build-system.sh
* Activate option in TUI to poetry and flit.
* Adding documentation about flit and poetry.
* Adding flit as a build-system:
* Creating a flit-pyproject.toml
* Editing post_gen_project.py
* Creating a smoke test (build-system.sh)
* Editing cookicutter.json
Solve #54 
This PR is a:
About this PR:
=> feat(template): Adding flit as a build-system option

src/scicookie/{{cookiecutter.project_slug}}/build-system/flit-pyproject.toml
The correct name in the pyproject.toml for `build_system=flit`  is the value in `project_slug`.
Thank you for the catch @YurelyCamacho 
This PR is a:
About this PR:
=> fix(variable name): Fix package's name

src/scicookie/{{cookiecutter.project_slug}}/Makefile, src/scicookie/{{cookiecutter.project_slug}}/build-system/flit-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/poetry-pyproject.toml, tests/smoke/base.sh
This PR aims to fix the tests for different build-systems
* ```...```
This PR is a:
About this PR:
```
```
=> test: fix smoke tests for build-system

.github/workflows/main.yaml, README.md, docs/guide.md, src/scicookie/cookiecutter.json, src/scicookie/hooks/post_gen_project.py, src/scicookie/profiles/base.yaml, src/scicookie/{{cookiecutter.project_slug}}/Makefile, src/scicookie/{{cookiecutter.project_slug}}/build-system/flit-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/meson.build, src/scicookie/{{cookiecutter.project_slug}}/build-system/mesonpy-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/conda/dev.yaml, src/scicookie/{{cookiecutter.project_slug}}/docs-mkdocs/mkdocs.yaml, src/scicookie/{{cookiecutter.project_slug}}/docs/contributing.md, tests/smoke/base.sh, tests/smoke/build-system.sh
- Activate option in TUI to meson-python.
- Adding meson-python as a build-system:
- Creating a mesonpy-pyproject.toml
- Editing post_gen_project.py
- Adding mesonpy to build-system.sh
- Adding meson.build as additional configuration file
- Editing cookicutter.json
- Adding meson-python in conda/dev.yaml 
Solve #55
This PR is a:
- [x ] new feature
- [x ] maintenance
About this PR:
- [ x] pre-commit hooks were executed locally.
- [ x] this PR requires a project documentation update.
=> feat(template): adding meson-python as a build-system option

.github/workflows/main.yaml, .github/workflows/release.yaml, src/scicookie/{{cookiecutter.project_slug}}/.github/workflows/main.yaml, src/scicookie/{{cookiecutter.project_slug}}/.github/workflows/release.yaml
* ```...```
This PR is a:
About this PR:
```
```
=> chore(ci): Fix mamba installation on CI

.github/workflows/main.yaml, .github/workflows/release.yaml, README.md, poetry.lock, src/scicookie/{{cookiecutter.project_slug}}/.github/workflows/main.yaml, src/scicookie/{{cookiecutter.project_slug}}/.github/workflows/release.yaml
The section for maintainers of the project has been added. This is a list of the names of the current SciCookie maintainers, in alphabetical order, with their respective GitHub usernames.
Co-authored-by: @YurelyCamacho 
This PR is a:
About this PR:
=> perf(project information): Adding the maintainer section to readme

docs/guide.md, src/scicookie/{{cookiecutter.project_slug}}/README.md
The purpose of this PR is to add the documentation associated with the TUI elements and some information that may be useful to the user of the template.
Information added:
- Structure for SciCookie user guide
- Notes about the text-based user interface (TUI)
- Introduction for Project settings and Project tools
- Information for:
- Project layout
- Build system
- bandit
- black
- blue
- coverage
- flake8
- ruff
- Docker
- Podman
- kubernetes [*]
- Code of conduct
- Governance document
- Roadmap document
- Control Version
- Improving information about pytest and hypothesis.
- Fix a typo in the template README.md
[*] I added information, but I don't think it's implemented (confirm @xmnlab)
@YurelyCamacho will continue to add more information :D
This PR is a:
About this PR:
Author's …
=> perf(documentation): Adding structure and content to guide.md

src/scicookie/cli.py, src/scicookie/profiles/base.yaml, src/scicookie/profiles/osl.yaml
- The missing information was due to wrong variable names in `base.yaml` and `osl.yaml`, this is corrected in this PR.
- Fix a typo in cli.py
Solve #147 #121 
This PR is a:
About this PR:
=> fix(template): Solve missing information

docs/guide.md
Add the missing information to complete the user guide on the elements in the TUI.
- Improvements to the current text
The added information corresponds to:
- Introduction for The author of project and The information about the project sections.
- Command Line Interfaces: click and argparse.
- Documentation engine: mkdocs, sphinx and jupyter-book.
- Virtual environment: conda.
- Code formatter: blue.
- Code style and logic (code quality): isort, McCabe, Vulture, pydocstyle.
- Pre-commit verification: pre-commit.
This PR is a:
About this PR:
```
```
=> perf(documentation): Adding missing content to guide.md

src/scicookie/cookiecutter.json
Fixes #159 
* ```...```
This PR is a:
About this PR:
```
```
=> Make `black` "yes" and `blue` "no" by default

README.md
* ```...```
This PR is a:
About this PR:
```
```
=> Add Saransh as a maintainer

docs/guide.md, src/scicookie/cookiecutter.json, src/scicookie/{{cookiecutter.project_slug}}/.github/workflows/main.yaml, src/scicookie/{{cookiecutter.project_slug}}/.makim.yaml, src/scicookie/{{cookiecutter.project_slug}}/build-system/flit-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/hatch-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/maturin-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/mesonpy-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/pdm-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/poetry-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/pybind11-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/scikit-build-core-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/setuptools-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/conda/dev.yaml, tests/smoke/base.sh
Fixes #91 
Added Makim tool as makim. 
1. added makim as dependency in pyproject.toml(template)
2. added .makim.yaml file
3. changed base.sh file
4. changed ci file(main.yaml) changed
* ```...```
This PR is a:
About this PR:
```
```
=> feat(template) : Added automation tool as makim

src/scicookie/{{cookiecutter.project_slug}}/build-system/flit-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/hatch-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/maturin-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/mesonpy-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/pdm-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/pybind11-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/scikit-build-core-pyproject.toml
Fixes #183 
* ```...```
This PR is a:
About this PR:
```
```
=> `Typing :: Typed` should be optional

README.md, docs/guide.md, src/scicookie/cookiecutter.json, src/scicookie/hooks/post_gen_project.py, src/scicookie/profiles/base.yaml, src/scicookie/{{cookiecutter.project_slug}}/.pre-commit-config.yaml, src/scicookie/{{cookiecutter.project_slug}}/.releaserc.json, src/scicookie/{{cookiecutter.project_slug}}/build-system/base-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/flit-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/hatch-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/maturin-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/mesonpy-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/pdm-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/poetry-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/pybind11-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/scikit-build-core-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/setuptools-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/{{cookiecutter.package_slug}}/__init__.py, src/scicookie/{{cookiecutter.project_slug}}/{{cookiecutter.package_slug}}/__main__.py, tests/smoke/auto-format-tools.sh
Removes the support of blue by modifying multiple files
Fixes #186 
* ```...```
This PR is a:
About this PR:
```
```
=> feat(formatter): remove support for blue formatter

.github/workflows/main.yaml, .prettierignore, .prettierrc.yaml, docs/contributing.md
* ```...```
This PR is a:
About this PR:
```
```
=> docs: Improve the Contributing Guide

docs/guide.md
Update of the guide with the inclusion of the option for the numfocus coc, which was missing in the previous PR about this
Solve #142 
This PR is a:
About this PR:
```
=> feat(upgrade): update guide with the option for NumFOCUS coc

docs/guide.md, src/scicookie/cookiecutter.json, src/scicookie/hooks/post_gen_project.py, src/scicookie/profiles/base.yaml, src/scicookie/profiles/osl.yaml, src/scicookie/{{cookiecutter.project_slug}}/coc/PYTHON_ADAPTED_COC.md, tests/smoke/files.sh
Adding the Python Code of Conduct option as an option in the template.
Edited files:
- src/scicookie/cookiecutter.json
- src/scicookie/hooks/post_gen_project.py
- src/scicookie/profiles/base.yaml
- src/scicookie/profiles/osl.yaml
- tests/smoke/files.sh
- 
New files:
src/scicookie/{{cookiecutter.project_slug}}/coc/PYTHON_ADAPTED_COC.md
Solve #143 
This PR is a:
About this PR:
=> feat(upgrade): adding python coc option

.github/PULL_REQUEST_TEMPLATE.md, src/scicookie/{{cookiecutter.project_slug}}/.github/PULL_REQUEST_TEMPLATE.md
Replaces 'fixes' with 'solves' in PULL_REQUEST_TEMPLATE.md to ensure issue linking with pull request as per https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
Fixes #217 
* ```...```
This PR is a:
About this PR:
```
```
=> chore(PULL_REQUEST_TEMPLATE.md): replace solves with fixes to ensure issue linking 

.git-blame-ignore-revs
Fixes #180 
@Saransh-cpp Thank you for your suggestion! 💯 🚀 
This PR is a:
About this PR:
complexity.
=> feat: support prettier 3/3

src/scicookie/hooks/post_gen_project.py, src/scicookie/{{cookiecutter.project_slug}}/.makim.yaml, src/scicookie/{{cookiecutter.project_slug}}/Makefile, src/scicookie/{{cookiecutter.project_slug}}/docs-mkdocs/mkdocs.yaml
Fixes #177 
This PR is a:
About this PR:
complexity.
=> imp: move the mkdocs.yaml file to the root

README.md
Adding the acknowledgements section in the readme to mention the grants received from the PSF.
Solve #210 
This PR is a:
About this PR:
=> docs(upgrade): adding acknowledge section

src/scicookie/{{cookiecutter.project_slug}}/.github/workflows/main.yaml
This pull request updates the CI configuration to ensure that it only executes for the main branch. This change is being made to streamline our CI process and ensure that tests and workflows are only triggered for changes made to the main branch.
Fixes #214 
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> ci(template): update ci configuration for main branch only

docs/contributing.md
Add section "How to Debug the tests" in contributing guide.  
This PR is a:
About this PR:
complexity.
```
=> docs(upgrade): add section in contributing guide

docs/contributing.md, docs/install.md, mkdocs.yaml
Added a new page for installation and a section for documentation development in `contributing.md`.
A small step towards #191 
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> docs(upgrade): add section in contributing guide and new installation page

src/scicookie/{{cookiecutter.project_slug}}/build-system/poetry-pyproject.toml
=> update poetry dev dependencies section format

src/scicookie/{{cookiecutter.project_slug}}/{{cookiecutter.package_slug}}/__init__.py, src/scicookie/{{cookiecutter.project_slug}}/{{cookiecutter.package_slug}}/__main__.py
Delete mypy filter #type: ignore from __main__.py file
Fixes #223 
-->
This PR is a:
About this PR:
complexity.
```
```
=> fix(file): remove mypy filter #type:ignore

README.md, docs/index.md
The scicookie templates aims to streamline the creation process by eliminating boilerplate structures. However, the project description was mistakenly categorized as boilerplate content. This pull request aims to rectify this misunderstanding and provide clarity regarding the project's description. 
Resolves #191
This PR is a:
About this PR:
complexity.
=> docs(upgrade): update documentation on README.md , index.md

src/scicookie/{{cookiecutter.project_slug}}/build-system/deps-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/poetry-pyproject.toml, tests/smoke/base.sh
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> ci: Fix smoke tests issues with mamba

src/scicookie/{{cookiecutter.project_slug}}/build-system/base-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/deps-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/flit-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/hatch-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/maturin-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/mesonpy-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/pdm-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/poetry-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/pybind11-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/scikit-build-core-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/setuptools-pyproject.toml
Fixes: #154 
This PR is a:
About this PR:
complexity.
```
=> imp: identation of the dependencies in the pyproject.toml file for the different build systems

src/scicookie/hooks/post_gen_project.py, src/scicookie/{{cookiecutter.project_slug}}/build-system/mesonpy/main.cpp, src/scicookie/{{cookiecutter.project_slug}}/build-system/mesonpy/meson.build, tests/smoke/base.sh
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> fix: Fix the generation for mesonpy build-system

src/scicookie/hooks/post_gen_project.py, src/scicookie/{{cookiecutter.project_slug}}/build-system/maturin/Cargo.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/maturin/lib.rs, tests/smoke/base.sh
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> fix: Fix generation for maturin build-system

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug-report.yml, README.md, docs/description.md, docs/index.md, poetry.lock, pyproject.toml, src/scicookie/__init__.py, src/scicookie/cli.py, src/scicookie/{{cookiecutter.project_slug}}/docs/index.md, tests/smoke/base.sh
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> fix: Move back to cookiecutter

.github/workflows/main.yaml, conda/dev-win.yaml, poetry.lock, pyproject.toml, src/scicookie/cli.py
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> fix: Fix usage of scicookie for pipx

poetry.lock, pyproject.toml, src/scicookie/cli.py, src/scicookie/profiles/base.yaml, src/scicookie/ui.py, tests/profiles/test-main.yaml, tests/test_cli.py
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> tests: Add tests for scicookie CLI

src/scicookie/profile.py, src/scicookie/ui.py, tests/profiles/test-depends-on.yaml, tests/test_cli.py
This PR aims to add support for conditional questions (depends_on)
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> feat: Add initial mechanism for conditional question

.github/workflows/main.yaml
Implemented caching for conda environment in ci, will add it to template after this is approved
Fixes #102 
Tested it on my own forked repository, check [PR](https://github.com/Naman-Priyadarshi/scicookie/pull/1) for this. Re-ran all the jobs to ensure caching is done.
This PR is a:
About this PR:
complexity.
```
```
=> ci(caching): add cache for conda environment in ci

src/scicookie/ui.py, tests/profiles/test-depends-on.yaml, tests/test_cli.py
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> feat: Add support for OR and AND for depends_on

src/scicookie/profiles/base.yaml, src/scicookie/ui.py, tests/profiles/test-depends-on.yaml, tests/test_cli.py
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> feat: Add support for jinja2 template in the visibility attribute

src/scicookie/{{cookiecutter.project_slug}}/docs-mkdocs/mkdocs.yaml
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> fix: Fix template issue for mkdocs

src/scicookie/{{cookiecutter.project_slug}}/.github/workflows/main.yaml, src/scicookie/{{cookiecutter.project_slug}}/.pre-commit-config.yaml
Implemented caching for conda environment in template's ci
Fixes #102 
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> ci(caching): add cache for conda environment in template ci and update ruff linter commands

src/scicookie/{{cookiecutter.project_slug}}/.pre-commit-config.yaml, src/scicookie/{{cookiecutter.project_slug}}/build-system/poetry/pyproject.toml
Fixing comment about semantic-release in poetry/pyproject.toml file
This PR is a:
About this PR:
complexity.
```
=> fix: Fix comment about semantic-release

src/scicookie/{{cookiecutter.project_slug}}/build-system/poetry/pyproject.toml
Add table (section) in the pyproject.toml for poetry build-system
Fixes #307 
-->
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> feat: Add section (table) build-system for poetry in the pyproject.toml 

poetry.lock, src/scicookie/{{cookiecutter.project_slug}}/virtualenvs/conda/dev.yaml
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> fix: Fix development dependencies issues with distlib and move from conda pkg build to python-build

src/scicookie/{{cookiecutter.project_slug}}/build-system/base/dev-deps-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/poetry/pyproject.toml
There was a restriction on griffe because quartodoc wasn't working, now it works fine, this restriction is removed here because it's not necessary.
This PR is a:
About this PR:
complexity.
=> fix(template): Removing griffe restriction

conda/dev.yaml, src/scicookie/hooks/post_gen_project.py, src/scicookie/{{cookiecutter.project_slug}}/build-system/base/dev-deps-config-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/base/dev-deps-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/poetry/pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/docs-mkdocs/mkdocs.yaml, src/scicookie/{{cookiecutter.project_slug}}/docs/api/references.md, src/scicookie/{{cookiecutter.project_slug}}/scripts/gen_ref_nav.py, src/scicookie/{{cookiecutter.project_slug}}/virtualenvs/conda/dev.yaml
Auto generation api documentation files for mkdocs
Fixes #309
- `...`
This PR is a:
About this PR:
complexity.
```
=> feat: Autogeneration api documentation files for mkdocs

.github/workflows/main.yaml, .pre-commit-config.yaml, conda/dev-win.yaml, conda/dev.yaml, poetry.lock, pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/base/dev-deps-config-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/base/dev-deps-pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/base/pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/build-system/poetry/pyproject.toml, src/scicookie/{{cookiecutter.project_slug}}/virtualenvs/conda/dev.yaml
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> fix: Remove support for python >3.12,<3.9

README.md, docs/description.md, docs/guide.md, docs/index.md, src/scicookie/{{cookiecutter.project_slug}}/README.md, src/scicookie/{{cookiecutter.project_slug}}/docs/contributing.md, src/scicookie/{{cookiecutter.project_slug}}/docs/index.md
Update information in files:
- Project: description.md, index.md, README.md
- Template: index.md, README.md, contributing.md
- `...`
This PR is a:
About this PR:
complexity.
=> doc: Update documentation for project and template

docs/contributing.md, docs/install.md
Updating installation instructions for mamba env: replacing `--force` by `--yes`
This PR is a:
About this PR:
complexity.
=> Updating installation instructions for mamba env

.github/workflows/stale.yaml, src/scicookie/{{cookiecutter.project_slug}}/.github/workflows/stale.yaml, src/scicookie/{{cookiecutter.project_slug}}/build-system/base/pyproject.toml
Add github workflow for closing stale prs in project and template
Fixes #340 
-->
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> Add github workflow for closing stale prs
